ar_arm:
  joints: &robot_joints
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  controllers:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    command:
      # position_controllers/JointTrajectoryController
      # pos_vel_controllers/JointTrajectoryController
      # pos_vel_acc_controllers/JointTrajectoryController
      type: position_controllers/JointTrajectoryController
      joints: *robot_joints
      constraints:
        # if zero, the executing duration would be decided by the start and end time of planned trajectory
        # set it big enough especially for position controller
        goal_time: 20.0 # 0.5 sec
        stopped_velocity_tolerance: 0.01 # 0.01 rad/s
        joint_1: { trajectory: 2.0, goal: 0.01 } #{ trajectory: 0.2, goal: 0.1 }
        joint_2: { trajectory: 2.0, goal: 0.01 } #{ trajectory: 0.2, goal: 0.1 }
        joint_3: { trajectory: 2.0, goal: 0.01 } #{ trajectory: 0.2, goal: 0.1 }
        joint_4: { trajectory: 2.0, goal: 0.01 } #{ trajectory: 0.2, goal: 0.1 }
        joint_5: { trajectory: 2.0, goal: 0.01 } #{ trajectory: 0.2, goal: 0.1 }
        joint_6: { trajectory: 2.0, goal: 0.01 } #{ trajectory: 0.2, goal: 0.1 }
      # when starting the controller or canceling a trajectory, position hold mode is entered
      # this parameter specifies the time it takes to bring the current state (position and velocity) to a stop
      # if zero, the controller stops at the actual position
      stop_trajectory_duration: 0.0 # sec
