controller_manager:
  ros__parameters:
    update_rate: 25

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.0
      joint_1: { trajectory: 0.2, goal: 0.1 }
      joint_2: { trajectory: 0.2, goal: 0.1 }
      joint_3: { trajectory: 0.2, goal: 0.1 }
      joint_4: { trajectory: 0.2, goal: 0.1 }
      joint_5: { trajectory: 0.2, goal: 0.1 }
      joint_6: { trajectory: 0.2, goal: 0.1 }
    speed_scaling:
      state_interface: speed_scaling/speed_scaling_factor
      # Setting the command interface currently would clash with the io_and_status_controller
      # This will probably be changed in the future.
      # command_interface: $(var tf_prefix)speed_scaling/target_speed_fraction_cmd

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.025
      goal_time: 2.0
      joint_1: { trajectory: 0.2, goal: 0.1 }
      joint_2: { trajectory: 0.2, goal: 0.1 }
      joint_3: { trajectory: 0.2, goal: 0.1 }
      joint_4: { trajectory: 0.2, goal: 0.1 }
      joint_5: { trajectory: 0.2, goal: 0.1 }
      joint_6: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: speed_scaling/speed_scaling_factor
