chin_arm:
  controllers:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 100
    position:
      type: position_controllers/JointTrajectoryController
      joints:
        - chin_joint_1 #1
        - chin_joint_2 #3
        - chin_joint_3 #6
        - chin_joint_4 #9
        - chin_joint_5 #11
        - chin_joint_6 #13
      constraints: # checking if following values are set being greater than 0.0
        goal_time: 0.5 # 0.5 sec
        chin_joint_1:
          trajectory: 1.5 # 0.5 rad 
          goal: 1.5 # 0.02 rad
        chin_joint_2:
          trajectory: 1.5
          goal: 1.5
        chin_joint_3:
          trajectory: 2.5
          goal: 2.0
        chin_joint_4:
          trajectory: 2.5
          goal: 2.5
        chin_joint_5:
          trajectory: 2.5
          goal: 2.0
        chin_joint_6:
          trajectory: 2.5
          goal: 2.0
