whi_arm_interface:
  sw_estop_topic: estop
  shutdown_patience: 5000 #ms
  velocity_scale: 1.0
  payload_weight: 0.0 # unit Kg
  payload_to_tcp: [0.0, 0.0, 0.0]
  hardware: socket #api
  startup_duration: 10 #s
  socket:
    addr: 192.168.58.2
    port: 8080
  api:
    addr: 192.168.58.2
  debug:
    print_tcp_feedback: false
