whi_arm:
  hardware_interface:
    loop_hz: 30 # hz
    hardware: 'socket'
    forward_dirs: [-1, -1, -1, -1, -1, -1]
    speed_rate: 20
    angular_velocities: [99, 99, 99, 99, 99, 99]
    angular_accelerations: [198, 198, 198, 198, 198, 198]
    socket:
      addr: '192.168.4.44'
      port: 9866 # 9866 port for crc, 9888 for terminated string
