whi_arm_interface:
  loop_hz: 50 # hz
  velocity_scale: 1.0
  payload_weight: 4.5 # unit Kg
  payload_to_tcp: [0, -0.17, 0.08]
  hardware: socket #jaka_api
  startup_duration: 10 #s
  lpf: 5
  socket:
    addr: 10.5.5.100
  jaka_api:
    addr: 10.5.5.100
  debug:
    print_tcp_feedback: false
